### ISSUE TITLE
Language links is broken 

### ISSUE THREAD

**Issue by developerworks** [fermyon/wasm-languages#29]
in webassembly-language-support.md  
HTTP 404

**Comment by flynnduism** [comment]
@developerworks are you browsing the languages here on GitHub?

The `*.md` here are the source files that are published to the web at [https://www.fermyon.com/wasm-languages/webassembly-language-support](https://www.fermyon.com/wasm-languages/webassembly-language-support), the urls are structured for that destination.

**Comment by vdice** [comment]
Note: if the issue is due to the structuring mentioned by @flynnduism, we may soon be able to support both; see https://github.com/fermyon/bartholomew/pull/70

**Comment by vdice** [comment]
I'm assuming this issue is no longer relevant; closing.
