### ISSUE TITLE
AssemblyScript removed support for WASI

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/wasm-languages#39]
The Tweet below from the official [AssemblyScript](https://twitter.com/AssemblyScript) Twitter account says that "we have removed support for WASI".

https://twitter.com/AssemblyScript/status/1561699214069047299

I suppose this calls for an update of the Web Assembly Specific Languages section.

<img width="620" alt="Screen Shot 2022-08-24 at 10 22 11 pm" src="https://user-images.githubusercontent.com/9831342/186417207-ba592bc8-5cb4-41be-a3a7-adebcc3cbf97.png">

**Comment by MaxGraey** [comment]
WASI has been removed from the code base, but the AS still supports WASI through https://github.com/AssemblyScript/wasi-shim. It's just that WASI is no longer the default built-in runtime & API

**Comment by tpmccallum** [comment]
Thank you @MaxGraey that makes complete sense.
Also thank you for the link, really appreciate it.
