### ISSUE TITLE
did AssemblyScript drop WASI support?

### ISSUE THREAD

**Issue by cartooph** [fermyon/wasm-languages#41]
https://twitter.com/AssemblyScript/status/1561699214069047299?t=X3pOX5eW7WmZ8ehNIp2PsA&s=19 
"A new week, a new major AssemblyScript version! Among general improvements, we have removed support for WASI and from now on consider WASI, derived proposals, the W3C's endorsement of its subgroup and the Bytecode Alliance's practices harmful to open Web standards. 💔"

**Comment by technosophos** [comment]
It did. And I was far enough behind the times that the docs that are now there are relevant once more. (I was so far behind that I missed updating the docs to use the "new" AS WASI support, which was then removed.)
