### ISSUE TITLE
Update languages to the new template

### ISSUE THREAD

**Issue by technosophos** [fermyon/wasm-languages#5]
The following languages need to be updated to use the new `tpl.md` template:

- [ ] TypeScript
- [x] Ruby
- [ ] R
- [ ] Scala
- [ ] Powershell (?)
- [x] Rust
- [x] Go
- [x] Zig
- [x] Grain
- [x] Erlang
- [x] Haskell
- [ ] Lisp

**Comment by vdice** [comment]
Is this issue still relevant?  I'm hoping we can close or move issues (to the wasm language guide's new home at https://github.com/fermyon/developer) in anticipation of archiving this repository.  Thanks!

**Comment by vdice** [comment]
Assuming stale; closing.
