### ISSUE TITLE
Languages that need examples

### ISSUE THREAD

**Issue by technosophos** [fermyon/wasm-languages#6]
The following languages need examples. (The guidelines for examples are in https://github.com/fermyon/wasm-languages/blob/main/about-examples.md)

- [ ] JavaScript
- [x] Python (Example here: https://www.fermyon.com/blog/python-wagi)
- [x] C# (Based on https://github.com/SteveSandersonMS/dotnet-wasi-sdk)
- [x] Ruby (Should be very similar to Python)
- [x] Swift (Example here: https://github.com/technosophos/example-swift-wasm)
- [x] Go (Example here: https://spin.fermyon.dev/go-components/)
- [x] Rust (Overly complex example here: https://github.com/deislabs/wagi-examples/tree/main/env_wagi)
- [x] Grain (Example here: https://github.com/deislabs/wagi-examples/tree/main/hello-wagi-grain)
- [x] Zig

**Comment by vdice** [comment]
I've created https://github.com/fermyon/developer/issues/1183; closing this issue.  Thank you!
